# Generated by Django 4.2.2 on 2023-06-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigentUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(null=True, unique=True, upload_to=''),
        ),
    ]
