# Generated by Django 4.2.2 on 2023-06-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigentUsers', '0002_alter_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userID',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_bondName',
            field=models.CharField(default=None, max_length=210, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_hashCode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_displayName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(null=True, unique=True, upload_to='users_images/%Y%m_users/'),
        ),
    ]
