# Generated by Django 4.2.2 on 2023-06-09 06:14

import aigentUsers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigentUsers', '0004_alter_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(null=True, unique=True, upload_to=aigentUsers.models.save_imagePath),
        ),
    ]
