# Generated by Django 4.2.2 on 2023-06-09 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aigentUsers', '0005_alter_user_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_image',
            new_name='pictureUrl',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userID',
            new_name='userId',
        ),
    ]
