# Generated by Django 4.2.2 on 2023-06-09 13:27

import aigentUsers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigentUsers', '0006_rename_user_image_user_pictureurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pictureUrl',
            field=models.ImageField(blank=True, null=True, upload_to=aigentUsers.models.save_imagePath),
        ),
    ]
