# Generated by Django 4.2.2 on 2023-06-09 13:34

import aigentUsers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aigentUsers', '0007_alter_user_pictureurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pictureContent',
            field=models.ImageField(blank=True, null=True, upload_to=aigentUsers.models.save_imagePath),
        ),
        migrations.AlterField(
            model_name='user',
            name='pictureUrl',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
