# Generated by Django 4.2.2 on 2023-06-09 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aigentUsers', '0008_user_picturecontent_alter_user_pictureurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pictureUrl',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to='aigentUsers.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='aigentUsers.user')),
            ],
            options={
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
